spring.application.name=immo-abidjan-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/immo_abidjan
spring.datasource.username=immo_user
spring.datasource.password=immo_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081
